services:
  # use chromedp/headless-shell as a headless browser instance
  chrome:
    image: chromedp/headless-shell:latest
    container_name: headless-chrome
    ports:
      - "9222:9222"
    shm_size: "2gb"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '3.0'    # Limit to 3 CPU cores
          memory: 2G     # Limit to 2GB of memory
        reservations:
          cpus: '1.0'    # Reserve at least 1 CPU cores
          memory: 1GB    # Reserve at least 1GB of memory

  # alpine-chrome:
  #   image: zenika/alpine-chrome:latest
  #   container_name: alpine-chrome
  #   ports:
  #     - "9222:9222"    # Map to a different host port to avoid conflict with existing chrome service
  #   shm_size: "2gb"      # Shared memory size for better performance
  #   restart: unless-stopped
  #   init: true
  #   command: [
  #     chromium-browser,
  #     "--headless",
  #     "--disable-gpu",
  #     "--no-sandbox",
  #     "--disable-setuid-sandbox",
  #     "--disable-dev-shm-usage",
  #     "--disable-sync",
  #     "--no-first-run",
  #     "--no-zygote",
  #     "--autoplay-policy=no-user-gesture-required",
  #     "--disable-software-rasterizer",
  #     "--use-fake-ui-for-media-stream",
  #     "--enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb",
  #     "--use-fake-device-for-media-stream",
  #     "--remote-debugging-address=0.0.0.0",
  #     "--remote-debugging-port=9222"
  #   ]
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9222/json/version"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '2.0'    # Limit to 2 CPU cores
  #         memory: 2G     # Limit to 2GB of memory
  #       reservations:
  #         cpus: '0.5'    # Reserve at least 0.5 CPU cores
  #         memory: 1GB    # Reserve at least 1GB of memory

  pdf-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-generator
    ports:
      - "8080:8080"
    volumes:
      - ./index.html:/app/index.html
    restart: unless-stopped
    depends_on:
      - chrome
    deploy:
      resources:
        limits:
          cpus: '1.0'    # Limit to 1 CPU cores
          memory: 1G     # Limit to 1GB of memory
        reservations:
          cpus: '0.5'    # Reserve at least 0.5 CPU cores
          memory: 512M   # Reserve at least 512MB of memory
